uncss/uncss

package.json, src/phantom.js, src/uncss.js, src/utility.js, tests/coverage.js
I'm trying to use phantom.openPage to see if we can tell phantom where to look for JS files.
=> Tell PhantomJS where to look for files

src/phantom.js
* Exit function only called in one place.
* `isWindows` doesn't need to be passed to `ResourceHandler`.
* Extract `options.timeout` callback.
=> Clean up phantom.js

bin/uncss, src/lib.js, src/uncss.js, src/utility.js
Nicer to test against whether the array has the `length` property in these cases. :smiley:
=> Clean up usage of length.

src/phantom.js
As issue #150 explains, there's a problem with fromLocal() since commit 9b032eeb and this patch solves the problem until someone can properly fix it.
=> Revert fromLocal() to fix #150

README.md
=> Add docs for PostCSS plugin

package.json
I'm hoping this will fix https://github.com/giakki/uncss/issues/247
=> Move async from devDependencies to dependencies, since it's actually used by uncss.js

src/lib.js, tests/coverage.js
@giakki 
I'm finding it useful to list the unused Selectors in my report
=> Add unused selectors to report

README.md, bin/uncss, src/uncss.js, src/utility.js, tests/coverage.js
Hello!
This is my naive implementation of optional banner in result.
For now, I'm not sure how to handle missing banner in `parseErrorMessage` and if that's actually needed.
What do you think about this feature?
=> Add banner option to disable default uncss banner.

README.md, src/lib.js, tests/coverage/ignore_comment.css
Fixes #300 
Supersedes and closes #303
=> Allow ignoring whole blocks of rules with uncss:ignore comment

README.md
=> Clarify what uncss cannot do

.eslintrc.json, bin/uncss, package-lock.json, package.json, src/jsdom.js, src/lib.js, src/uncss.js, src/utility.js, tests/coverage.js, tests/errors.js, tests/glob.js, tests/jsdom.js, tests/jsdom/external_script.js, tests/mediaquery.js, tests/postcss.js, tests/rawhtml.js, tests/resemble.js, tests/selectors.js, tests/url.js
Note that this PR is against the `develop` branch.
I don't know if we should upgrade the JS API to either switch to Promises only, or support both Promises and callbacks. Thoughts?
=> Modernize code

src/lib.js, tests/output/selectors/uncss.css, tests/selectors/fixtures/keyframes.css
Fixes #284 
Note that this is based against `develop`. Sorry about the messy diff, I merged two functions into one.
=> Handle animation property correctly

package-lock.json, package.json
This should fix the build errors.
=> Update devDependencies and version in package files.

README.md, src/utility.js, tests/url.js
This PR addresses the issues in #329.
=> Support explicitly passing in local files in options.stylsheets

README.md, src/jsdom.js
=> Allow user to disable strictSSL checking in jsdom request

src/uncss.js
=> Return the promises to the caller

package-lock.json, package.json, src/jsdom.js, src/uncss.js, tests/jsdom.js, tests/jsdom/not_found.html, tests/postcss.js
=>  Add missing mapping of jsdom options in postcss plugin

README.md
=> fix:README file Missing a comma

package-lock.json, package.json
See <https://github.com/request/request/issues/3142>
=> Replace request (deprecated) with @root/request (drop-in).

package-lock.json, package.json, tests/output/selectors/uncss.css
This updates to postcss 8
The changes do not affect uncss
https://github.com/postcss/postcss/releases/tag/8.0.0
Closes https://github.com/uncss/uncss/pull/437
=> Update to Postcss8
