uncss/uncss

src/lib.js
Regex has been updated to allow for an optional, leading `!` which will prevent it from being stripped by CSS minifiers/tools such as grunt-contrib-concat and grunt-cssmin. This will increase the flexibility of using grunt-uncss within various points of the task order.
=> Make uncss:ignore survive CSS minifiers

src/uncss.js
Dropped timeout here, because phantom.fromRaw expects files and option-Object, not files and timeout. fromRaw calls resolveWithPage after promise is solved and in there option.timeout is used, not only option, which would contain the timeout. 
Use this Repo to reproduce the bug: https://github.com/marcelwagner/uncss-bug-example
**Start to use the repo by, cloning it to local disk.
Install npm-dependencies.
Run gulp css.**
As you can see, the task takes under 20 seconds. But I configured in the gulpfile.js that the phantomjs-instance should wait for 20 seconds.
```javascript
...
line 10:         timeout: 20000
...
```
If you use my branch: *gulp_timeout_patch* for it, phantomjs will wait 20 secounds before it will get back the html. This you can see by the time the task runs and if you …
=> Overhand files and option-Object, not files and timeout

bin/uncss
The command line client does'nt pick up regexes like it should for regexes in `options.ignoreSheets`. It currently only converts regexes in `options.ignore`.
This PR fixes that.
=> options.ignoreSheets regexes not picked up on CLI

README.md
Updated README to mention that `glob` file patterns are accepted.
I was confused if I could specify file path patterns or no, I openned and closed an issue #215 regarding to it
Now, I've checked the implementation, and I've seen that it's used https://github.com/giakki/uncss/blob/master/src/uncss.js#L30 so I would have more clear with a note similar to this in README.
=> Updated README to mention `glob`

src/lib.js
This PR supersedes #244 and fixes #188.
It uses the postcss.list module (http://api.postcss.org/list.html) for safer splitting of values (i.e. `postcss.list.space('1px calc(10% + 1px)') //=> ['1px', 'calc(10% + 1px)']`).
@XhmikosR @mikelambert I'd be willing to write tests for this but I'm unsure how your testing system works.
=> Support comma-seperated animation properties

tests/output/selectors/index.html, tests/output/selectors/uncss.css, tests/selectors/expected/keyframes.css, tests/selectors/fixtures/keyframes.css, tests/selectors/index.html
As discussed in https://github.com/giakki/uncss/pull/245.
I also added some instructions to `/tests/selectors/index.html`, advising of the things I got bitten with when adding these tests:
> - Placing any `<div>` elements on this page other than
div#battleground will break the "not" test!
- Any changes made here **must** be reflected in
/tests/output/selectors/index.html; otherwise, the
"Pages should resemble the reference:Selectors" test
will fail!
CC: @mikelambert
=> Add more tests for @keyframes

tests/phantomjs.js
The numbers are pretty random found with trial and error, but tests seem to pass now on Windows too.
=> Bump tests timeout to fix Windows tests.

src/lib.js, tests/coverage.js
@giakki 
I had a bug (#254) with the `report['selectors']['all']` being empty. I fixed it by concatting correctly, I matched how you do it in `getUsedSelectors`
Also added a test for it.
=> Issue 254 get all selectors fix

.travis.yml, appveyor.yml, package.json, src/uncss.js
The only issue is that tests fail on Windows. This is from my Windows 7 x64 dev VM since AppVeyor fails with an other error, possibly due to different node.js/npm versions:
```
C:\Users\xmr\Desktop\uncss>node -v && npm -v
v4.4.7
2.15.8
C:\Users\xmr\Desktop\uncss>npm test
> uncss@0.14.1 test C:\Users\xmr\Desktop\uncss
> grunt test
70 passing (2m)
2 failing
1) PhantomJS Should exit only when JS evaluation has finished:
Error: timeout of 25000ms exceeded. Ensure the done() callback is being called in this test.
at null.<anonymous> (C:\Users\xmr\Desktop\uncss\node_modules\grunt-mocha-cov\node_modules\mocha\lib\runnable.js:170:19)
at Timer.listOnTimeout (timers.js:92:15)
2) PhantomJS Should not wait for timeouts by default:
Error: timeout of 20000ms exceeded. Ensure the done() callback is …
```
=> Update dependencies and drop node.js 0.12 support.

src/phantom.js
Change the arguments passed to phridge.spawn to resemble the actual cli
arguments. If they do not start with a '-', phridge strips them out
before spawning PhantomJS.
=> Fix incorrect phridge arguments

src/lib.js
`dePseudify()` strips [several pseudo classes](https://github.com/giakki/uncss/blob/62a6841c423e019595204e1f476cdd0b8a821e9b/src/lib.js#L12) off of selectors such that the processing done by `filterUnusedSelectors()` can determine whether the "parent" selector is actually used or not.
I *believe* that the form validation-related pseudo classes ([`:required`](https://developer.mozilla.org/en-US/docs/Web/CSS/:required), [`:invalid`](https://developer.mozilla.org/en-US/docs/Web/CSS/:invalid), [`:valid`](https://developer.mozilla.org/en-US/docs/Web/CSS/:valid), e.g. as used in Bootstrap 4 Beta) should be given this same treatment.
Without this, [the `document.querySelector()` call in `findAll()` raises an exception](https://github.com/giakki/uncss/blob/62a6841c423e019595204e1f476cdd0b8a821e9b/ …
=> Also ignore form validation (:required, :invalid, :valid) pseudo classes

.travis.yml, appveyor.yml, package-lock.json, package.json, src/jsdom.js
* jsdom to v11.3.0; note that we are still using the old API.
* chai to v4.1.2
* coveralls to v3.0.0
* mocha to v4.0.0
Also, jsdom requires node.js >= 6 now so make that the required version.
/CC @mikelambert @RyanZim
=> Update all dependencies to the latest versions.

README.md, bin/uncss, src/jsdom.js, src/uncss.js, tests/jsdom.js, tests/jsdom/jsdom.css, tests/jsdom/useragent.html
We have adaptive css, ie you get different styles based on whether you're on desktop/tablet/mobile/whatever, so I was hoping you could pull this guy to let me configure the user agent that jsdom uses.
=> Adding user agent string as an available option

src/lib.js, tests/output/selectors/uncss.css, tests/selectors/expected/pseudo-class-with-pseudo-element.css, tests/selectors/fixtures/pseudo-class-with-pseudo-element.css, tests/selectors/index.html, tests/selectors/unused/pseudo-class-with-pseudo-element.css
Between 0.15.0 and 0.16.0, `dePseudify()` seemed to start mishandling selectors that have multiple pseudos, which isn't a case well-represented in the test suite but does occur in the wild (e.g. in Bootstrap 4).
I'm including here a failing test and a possible fix.
---
On 0.15.0:
```
$ echo '<p class="used">Hi</p>' | ./bin/uncss --raw '.used { color: red } .unused:visited::before { content: "a" }'
.used { color: red }
```
On master / 0.16.0:
```
$ echo '<p class="used">Hi</p>' | ./bin/uncss --raw '.used { color: red } .unused:visited::before { content: "a" }'
.used { color: red } .unused:visited::before { content: "a" }
```
I bisected this to 0170fe1a843c7c6d90c89647ece20c80558b141f (#345), which I think is the culprit.
That `pseudosRegex = new RegExp('([^\\\\])(' + …
=> Fix regression with dePseudify() if there are multiple pseudos that are to be ignored

package-lock.json, package.json, src/lib.js, tests/depseudify.js
Additionally, adds the `:focus-within` pseudo class and adds support for stripping pseudos even if they aren't all lowercase. Includes some tests that would have failed under the old "entire line at once" regex method.
Fixes #349.
Fixes #351.
=> Use postcss-selector-parser for dePseudify()

README.md
I noticed there wasn't a banner config option in the js example. I had to do a bit of fiddling with `noBanner: true` before I got the actual option right. Figured it would be easier to just include it in the readme 😄
=> Include banner in options example

src/uncss.js
The error occurs when multiple sets of files are processed as lodash's defaults method mutates the object. So on the second iteration of uncss `options` object has all the data from previous iteration including `html` that fails check in process method
=> Avoid of options mutation

src/jsdom.js, tests/jsdom.js, tests/jsdom/console.html
When using the cli to redirect output to a file, `console.log` statements within scripts will end up in the resulting css. As brought up in uncss/uncss#385, this uses the virtual console to redirect all console output to `stderr`.
=>  Redirect stdout (console.log) to stderr

README.md, bin/uncss
Using stdout sometimes results in extra information (console.log statements) being included in the output. This adds an option for outputting the resulting CSS to a file rather than just stdout.
I was focused on getting my particular use-case satisfied. Let me know if I can do better/more.
=> Add output option for cli

src/utility.js, tests/bom.js, tests/input/testbom.html, tests/input/with_bom.css
When the css file starts with the Byte Order Mark and the first line is
@namespace, the parser fails:
```
|| <css input>:2:1: Unknown word
|| 	1:        /*** uncss> filename: tests/input/with_bom.css ***/
|| 	2:     -> @namespace testbom "http://bom.for_utf8.com";
```
The solution taken to deal with it is to strip the BOM at the beginning of the file.
It doesn't seem to be problematic with @media or with @import
=> Fix parsing error when css starts with BOM

bin/uncss
Fixes a typo
TypeError: console.err is not a function:
https://github.com/uncss/uncss/blob/d0adf4bb89ef4f82006f8dd5b40d22a94269e50a/bin/uncss#L86
=> replaces console.err (not a function) by console.log
